### DISCUSSION TITLE
Papermerge config

### DISCUSSION THREAD

**Discussion by Nollknolle** [papermerge/papermerge-core#27] [Q&A]
Hey,
i would like to run papermerge with the automatic import.
how can i use that? how should i use the papermerge.conf.py?

i use it as docker-compose:
```
version: '3.7'
# Any top-level key starting with x- in a Docker Compose file will be
# ignored
x-backend: &backend  # yaml anchor definition
  image: ghcr.io/papermerge/papermerge:latest
  volumes:
    - media_root:/app/media
    - /share/papermerge:/media
  environment:
    # PAPERMERGE__<section>__<variable>
    - PAPERMERGE__MAIN__SECRET_KEY=XXXXX
    - PAPERMERGE__DATABASE__TYPE=XXXXX
    - PAPERMERGE__DATABASE__USER=XXXXX
    - PAPERMERGE__DATABASE__NAME=XXXXX
    - PAPERMERGE__DATABASE__PASSWORD=XXXXX
    - PAPERMERGE__DATABASE__HOST=XXXXX
    - PAPERMERGE__REDIS__HOST=XXXXX
    - PAPERMERGE__REDIS__PORT=XXXXX
    - PAPERMERGE__ELASTICSEARCH__HOSTS=XXXXX
    - PAPERMERGE__ELASTICSEARCH__PORT=XXXXX
    - PAPERMERGE__MAIN__TIMEZONE=XXXXX
    - DJANGO_SUPERUSER_USERNAME=XXXXX
    - DJANGO_SUPERUSER_EMAIL=XXXXX
    - DJANGO_SUPERUSER_PASSWORD=XXXXX
    - DJANGO_SETTINGS_MODULE=config.settings
services:
  worker: # celery worker
    <<: *backend
    command: worker
  ws_server:  # websockets server / daphne
    <<: *backend
    command: ws_server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ws_server.rule=Host(`papermerge.local`) && PathPrefix(`/ws/`)"
  backend:  # rest api backend / uwsgi
    <<: *backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`papermerge.local`) && PathPrefix(`/api/`)"
  db:
    image: postgres:14.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: 'redis:6'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'
  traefik:
    image: "traefik:v2.6"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  frontend: # emberjs
    image: ghcr.io/papermerge/papermerge.js:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`papermerge.local`) && PathPrefix(`/`)"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
volumes:
  postgres_data:
  media_root:
  redisdata:
```

URL: https://docs.papermerge.io/User's%20Manual/consumption.html?highlight=papermerge%20conf%20py#the-importer-directory

i found nothing in the docs...

thanks in advance
