### ISSUE TITLE
Upgrade from docker image 2.1.9 to 3.0 doesn't seem to work

### ISSUE THREAD

**Issue by nodje** [papermerge/papermerge-core#293]
error in logs:
```
Installing the current project: auth-server (0.6.1)
papermerge  | Traceback (most recent call last):
papermerge  |   File "<string>", line 1, in <module>
papermerge  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
papermerge  |     return _bootstrap._gcd_import(name[level:], package, level)
papermerge  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
papermerge  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
papermerge  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
papermerge  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
papermerge  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
papermerge  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
papermerge  |   File "/auth_server_app/auth_server/cli/create_user.py", line 5, in <module>
papermerge  |     from auth_server.database.engine import engine
papermerge  |   File "/auth_server_app/auth_server/database/__init__.py", line 1, in <module>
papermerge  |     from .session import get_db
papermerge  |   File "/auth_server_app/auth_server/database/session.py", line 2, in <module>
papermerge  |     from .engine import engine
papermerge  |   File "/auth_server_app/auth_server/database/engine.py", line 5, in <module>
papermerge  |     settings = get_settings()
papermerge  |   File "/auth_server_app/auth_server/config.py", line 37, in get_settings
papermerge  |     return Settings()
papermerge  |   File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
papermerge  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
papermerge  | pydantic.error_wrappers.ValidationError: 1 validation error for Settings
papermerge  | papermerge__security__secret_key
papermerge  |   field required (type=value_error.missing)
papermerge  | /usr/lib/python3/dist-packages/supervisor/options.py:474: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
papermerge  |   self.warnings.warn(
papermerge  | 2024-01-06 19:06:04,724 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
```

config :
```
 papermerge:
    image: papermerge/papermerge:2.1.9
    restart: always
    container_name: papermerge
#    user: 2012:2012
    environment:
      - PAPERMERGE__MAIN__SECRET_KEY=${PAPERMERGE_SECRET_KEY}
      - DJANGO_SUPERUSER_USERNAME=nodje
      - DJANGO_SUPERUSER_PASSWORD=${PAPERMERGE_SUPERUSER_PASSWORD}
#      - PAPERMERGE__MAIN__LOGGING_CFG=/etc/papermerge/logging.yaml
      - PAPERMERGE__MAIN__MEDIA_ROOT=/media
    networks:
      - default
    volumes:
     - /mnt/data/papermerge/media:/media
 ```
 
 Revert to 2.1.9 worked
