### ISSUE TITLE
Migrate from 2.1 to 3.4

### ISSUE THREAD

**Issue by ciur** [papermerge/papermerge-core#588]
Now it is time to say farewell to 2.1. 
This ticket is about creation migration scripts and helping community to migrate from 2.1 to 3.4

**Comment by ciur** [comment]
Is there anybody interested in migrating from 2.1 to 3.4 ? If yes, now is the moment to raise your hand.
If there will be no interest until June 2025, I will close the topic.

**Comment by RFPSM** [comment]
Yes, I'm interested in migrating from 2.1 to 3.4.

**Comment by ciur** [comment]
@RFPSM could you please post your docker compose  + configurations similarly how it is done [here ](https://github.com/papermerge/papermerge-core/discussions/589#discussioncomment-12126065)?

The point here of course is that I can reproduce locally your environment so that I can test
migration tool. Migration tool is still work in progress. Will be out in a week or so.

**Comment by RFPSM** [comment]
@ciur Yes, I have a simple setup with a Synology NAS as the docker platform and was setup in Portainer. Thanks for your help.

My compose file
```
version: '3.7'
x-backend: &backend
  image: papermerge/papermerge:2.1.9
  volumes:
    - /volume1/docker/papermerge/media:/app/media
    - xapian_index:/app/xapian_index
  environment:
    - PAPERMERGE__MAIN__SECRET_KEY=${SECRET_KEY}
    - PAPERMERGE__DATABASE__TYPE=postgres
    - PAPERMERGE__DATABASE__USER=${DB_USER}
    - PAPERMERGE__DATABASE__NAME=${DB_NAME}
    - PAPERMERGE__DATABASE__PASSWORD=${DB_PASSWORD}
    - PAPERMERGE__DATABASE__HOST=${DB_HOST}
    - PAPERMERGE__REDIS__HOST=redis
    - PAPERMERGE__REDIS__PORT=6379
    - PAPERMERGE__SEARCH__PATH=/app/xapian_index
    - DJANGO_SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
    - DJANGO_SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
    - DJANGO_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    - DJANGO_SETTINGS_MODULE=config.settings
services:
  worker:
    <<: *backend
    command: worker
  backend:
    <<: *backend
    ports:
      - '16000:8000'
  db:
    image: postgres:14.4
    volumes:
      - /volume1/docker/papermerge/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  redis:
    image: 'redis:6'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
volumes:
  postgres_data:
  media_root:
  xapian_index:
  redis_data:
```
```
DB_USER=postgres
DB_NAME=postgres
DB_PASSWORD=postgres
DB_HOST=db
DB_PORT=5432
SECRET_KEY=***
SUPERUSER_USERNAME=***
SUPERUSER_EMAIL=***
SUPERUSER_PASSWORD=***
```
