### ISSUE TITLE
Container exit

### ISSUE THREAD

**Issue by schergr** [papermerge/papermerge-core#591]
Getting the following error on the ocr worker container (papermerge container starts fine). 

I've specified the UID, but the docker-compose doc's / examples aren't specific about exactly how. Any thoughts?

```
/root/.cache/pypoetry/virtualenvs/ocrworker-9TtSrW0h-py3.13/lib/python3.13/site-packages/celery/platforms.py:829: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!
Please specify a different user using the --uid option.
User information: uid=0 euid=0 gid=0 egid=0
  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@8e4d1c83ad0e v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- Linux-6.1.27-x86_64-with-glibc2.36 2025-03-06 21:33:13
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         ocrworker:0x7f107c93c1a0
- ** ---------- .> transport:   redis://shared-redis:6379/0
- ** ---------- .> results:     redis://shared-redis:6379/0
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> ocr              exchange=ocr(direct) key=ocr

```

My docker-compose files looks like this:
                                                                
```
services:
  papermerge:
    image: papermerge/papermerge:3.4
    environment:
      - UID=999
      - PAPERMERGE__SECURITY__SECRET_KEY=12345
      - PAPERMERGE__AUTH__USERNAME=admin
      - PAPERMERGE__AUTH__PASSWORD=admin
      - PAPERMERGE__DATABASE__URL=postgresql://admin:admin!@shared-database-db-1:5432/pmgdb
      - PAPERMERGE__REDIS__URL=redis://shared-redis:6379/0
      - PAPERMERGE__MAIN__MEDIA_ROOT=/var/media/pmg
      - PAPERMERGE__MAIN__TIMEZONE=America/New_York
    networks:
      - shared-services-network
      - db-network 
    volumes:
      - /volume3/mydocs/docmgmt/media/docs:/var/media/pmg
    ports:
     - 12000:80
  ocr_worker:
    image: papermerge/ocrworker:0.3.1
    command: worker
    environment:
      UID: 999
      PAPERMERGE__DATABASE__URL: postgresql://admin:admin@shared-database-db-1:5432/pmgdb
      PAPERMERGE__REDIS__URL: redis://shared-redis:6379/0
      PAPERMERGE__MAIN__MEDIA_ROOT: /var/media/pmg
      OCR_WORKER_ARGS: "-Q ocr -c 2"
    volumes:
      - /volume3/mydocs/docmgmt/media/docs:/var/media/pmg
    networks:
      - shared-services-network
      - db-network
networks:
  monitoring-network:
    external: true
  db-network:
    external: true
  shared-services-network:
    external: true
```
